name: llm-vla-orchestrator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pillow>=8.3.1,<9
  - pyyaml>=6,<7
  - pip:
      - chess==1.11.2
      - langsmith>=0.3.16
      - openai==2.21.0
      - scipy==1.10.1
      - "chesscog @ git+https://github.com/georg-wolflein/chesscog.git@4e9c22d76c75615d4e9a4cd567679f4caa00dec7"
